name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: vscode-browser-docker
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run TruffleHog
        run: |
          docker pull dxa4481/trufflehog
          docker run -v ${{ github.workspace }}:/target dxa4481/trufflehog --entropy=False file:///target
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: antiantiops/vscode-browser-docker:latest, antiantiops/vscode-browser-docker:${{ env.RELEASE_VERSION }}
      - name: Run Trivy vulnerability scanner (CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: antiantiops/vscode-browser-docker:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          trivyIgnores: 'request-trivy-ignore.txt'
          #https://github.com/aquasecurity/trivy/issues/4826
          #skip-files: '/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sts@v1.21.4/api_op_GetAccessKeyInfo.go'
          #skip-dirs: '/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service'
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: antiantiops/vscode-browser-docker:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH'